# Generated by Django 4.1.1 on 2025-04-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_alter_hospital_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='district',
            field=models.CharField(choices=[('Mitte', 'Mitte'), ('Friedrichshain-Kreuzberg', 'Friedrichshain-Kreuzberg'), ('Pankow', 'Pankow'), ('Charlottenburg-Wilmersdorf', 'Charlottenburg-Wilmersdorf'), ('Spandau', 'Spandau'), ('Steglitz-Zehlendorf', 'Steglitz-Zehlendorf'), ('Tempelhof-Schöneberg', 'Tempelhof-Schöneberg'), ('Neukölln', 'Neukölln'), ('Treptow-Köpenick', 'Treptow-Köpenick'), ('Marzahn-Hellersdorf', 'Marzahn-Hellersdorf'), ('Lichtenberg', 'Lichtenberg'), ('Reinickendorf', 'Reinickendorf')], max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hos_type',
            field=models.CharField(choices=[('Berlin Headquarters Hospital', 'Berlin Headquarters Hospital'), ('Medical College Hospital', 'Medical College Hospital'), ('Family Health Center', 'Family Health Center')], max_length=100),
        ),
    ]
